[".config/git/alias"]
  type = "file"
  url = "https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt"
  refreshPeriod = "168h"
[".config/fish/completions/hub.fish"]
  type = "file"
  url = "https://raw.githubusercontent.com/github/hub/master/etc/hub.fish_completion"
  refreshPeriod = "168h"
{{- if (not .headless) }}
{{-   $fontDir := "" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}
["{{ $fontDir }}/Fira Code Medium Nerd Font Complete Windows Compatible.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Medium/complete/Fira%20Code%20Medium%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Fira Code Regular Nerd Font Complete Windows Compatible.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Fira Code Retina Nerd Font Complete Windows Compatible.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Retina/complete/Fira%20Code%20Retina%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf"
    refreshPeriod = "168h"
[".config/wezterm/colors/nightfox.toml"]
    type = "file"
    url = "https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_wezterm.toml"
    refreshPeriod = "168h"
[".config/wezterm/colors/duskfox.toml"]
    type = "file"
    url = "https://github.com/edeneast/nightfox.nvim/raw/main/extra/duskfox/nightfox_wezterm.toml"
    refreshPeriod = "168h"
{{- end }}
