#!/usr/bin/env bash

[ -z "$PS1" ] && return

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

shopt -s checkwinsize
shopt -s histappend

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if [[ -f ~/.bash_aliases ]]; then
  . "$HOME/.bash_aliases"
fi

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if [[ $(command -v direnv) ]]; then
  eval "$(direnv hook bash)"
fi

if [[ -d $HOME/.asdf ]]; then
  . "$HOME/.asdf/completions/asdf.bash"
fi

if [[ $(command -v zoxide) ]]; then
  eval "$(zoxide init bash)"
fi

if [[ $(command -v starship) ]]; then
  eval "$(starship init bash)"
fi
