[env]
# supports arbitrary env vars so rtx can be used like direnv/dotenv
# NODE_ENV = 'production'

[tools]
# specify single or multiple versions
bat = 'latest'
fd = 'latest'
github-cli = 'latest'
neovim = 'nightly'
nodejs = 'lts'
ripgrep = 'latest'

# supports everything you can do with .tool-versions currently
# nodejs = ['16', 'prefix:20', 'ref:master', 'path:~/.nodes/14']

# send arbitrary options to the plugin, passed as:
# RTX_TOOL_OPTS__VENV=.venv
# python = {version='3.10', virtualenv='.venv'}

[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
# python = 'https://github.com/jdxcode/rtx-python'
