vim.fn['altercmd#load']()

vim.cmd 'AlterCommand c[apture] Capture'
vim.cmd 'AlterCommand dc[lose] DiffviewClose'
vim.cmd 'AlterCommand df[ile] DiffviewFileHistory'
vim.cmd 'AlterCommand do[pen] DiffviewOpen'
vim.cmd 'AlterCommand dr[efresh] DiffviewRefresh'
vim.cmd 'AlterCommand g[sigins] Gitsigns'
vim.cmd 'AlterCommand ng[it] Neogit'
vim.cmd 'AlterCommand not[ify] Notifications'
vim.cmd 'AlterCommand pcl[ean] PackerClean'
vim.cmd 'AlterCommand pco[mpile] PackerCompile'
vim.cmd 'AlterCommand pin[stall] PackerInstall'
vim.cmd 'AlterCommand pst[atus] PackerStatus'
vim.cmd 'AlterCommand psy[nc] PackerSync'
vim.cmd 'AlterCommand pup[date] PackerUpdate'
vim.cmd 'AlterCommand ppr[ofile] PackerProfile'
vim.cmd 'AlterCommand sed[elete] DeleteSession'
vim.cmd 'AlterCommand ses[earch] SearchSession'
vim.cmd 'AlterCommand snc[lose] SnipClose'
vim.cmd 'AlterCommand snr[un] SnipRun'
vim.cmd 'AlterCommand t[elescope] Telescope'
vim.cmd 'AlterCommand tc[lose] ToggleTermCloseAll'
vim.cmd 'AlterCommand te[xec] TermExec<Space>cmd'
vim.cmd 'AlterCommand to[pen] ToggleTermOpenAll'
