# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
symlink = "ln -sf {{ files.0 }} {{ dir }}/_{{ name }}" # only uses first matched file

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autocomplete-local]
local = "~/.config/zsh"
use = ["autocomplete.zsh"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-auto-notify]
github = "MichaelAquilina/zsh-auto-notify"

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{directories,key-bindings}.zsh"]

[plugins.ohmyzsh-plugins-asdf]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["asdf/*.zsh"]

[plugins.fzf]
inline = 'FZF_BASE="$(asdf where fzf)"'

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{aws,direnv,docker,fzf,globalias,npm}/*.zsh"]

[plugins.ohmyzsh-plugins-fd]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/fd"
apply = ["fpath"]

[plugins.ohmyzsh-plugins-ripgrep]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/ripgrep"
apply = ["fpath"]

[plugins.chezmoi]
remote = "https://raw.githubusercontent.com/twpayne/chezmoi/master/completions/chezmoi.zsh"
apply = ["symlink", "fpath"]

[plugins.sheldon]
remote = "https://raw.githubusercontent.com/rossmacarthur/sheldon/trunk/completions/sheldon.zsh"
apply = ["symlink", "fpath"]

[plugins.zoxide]
remote = "https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/contrib/completions/_zoxide"
apply = ["fpath"]

[plugins.init]
inline = '''
(( $+commands[zoxide] )) && eval "$(zoxide init zsh)"
(( $+commands[starship] )) && eval "$(starship init zsh)"
'''

[plugins.local]
local = "~/.config/zsh"
use = ["*.zsh", "!autocomplete.zsh"]
