#!/usr/bin/env zsh

export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

export EDITOR="nvim"
export VISUAL="nvim"
export MANPAGER='nvim +Man!'
export MANWIDTH=999

export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME"/asdf/config
export ASDF_DATA_DIR="$XDG_DATA_HOME"/asdf
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME"/ripgrep/config
export STARSHIP_CONFIG="$XDG_CONFIG_HOME"/starship/starship.toml

ZDOTDIR="$XDG_CONFIG_HOME"/zsh

HISTFILE="$XDG_STATE_HOME"/zsh/history
HISTORY_IGNORE="(l[sal]|cd|pwd|v|zsh)"
HISTSIZE=50000
SAVEHIST=10000

WORDCHARS="*?_-.[]~=&;!#$%^(){}<>"

skip_global_compinit=1

typeset -U path PATH
typeset -U cdpath CDPATH

path=(
  $HOME/bin(N-/)
  $HOME/.local/bin(N-/)
  $path
)

cdpath=(
  $HOME/*(N-/)
  $cdpath
)

export GPG_TTY="$(tty)"
