name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on macos
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Install requisites on ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo add-apt-repository ppa:fish-shell/release-3
          sudo apt-get update

      - name: Chezmoi Init
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro

  centos:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on centos
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on fedora
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro
