---
name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Install requisites (macos)
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Install requisites (ubuntu)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo add-apt-repository ppa:fish-shell/release-3
          sudo apt-get update

      - name: Chezmoi Init
        if: ${{ runner.os != 'Windows' }}
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro

      - name: Chezmoi Init (windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          (irm -useb https://chezmoi.io/get.ps1) | powershell -c -
          bin/chezmoi.exe init --apply gametaro
  # centos:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   container: centos:latest
  #   steps:
  #     - uses: actions/checkout@v3
  #
  #     - name: Install requisites (centos)
  #       run: dnf clean all && dnf install -y curl sudo
  #
  #     - name: Chezmoi Init
  #       run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro

  fedora:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install requisites (fedora)
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro
