name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Chezmoi init & apply
        run: ./install.sh
  macos:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Chezmoi init & apply
        run: ./install.sh
  windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Chezmoi init & apply
        shell: pwsh
        run: |
          (irm -useb https://get.chezmoi.io/ps1) | powershell -c -
          bin/chezmoi.exe init --apply --source $Env:GITHUB_WORKSPACE
  centos:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: quay.io/centos/centos:stream
    steps:
      - uses: actions/checkout@v3
      - name: Install requisites
        run: dnf clean all && dnf install -y -q curl sudo
      - name: Chezmoi init & apply
        run: ./install.sh
  fedora:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requisites
        run: dnf clean all && dnf install -y -q curl sudo
      - name: Chezmoi init & apply
        run: ./install.sh
