---
name: CI
on: [push, pull_request]

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned

      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on macos
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Install requisites on ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install -y curl sudo

      - name: Chezmoi Init
        run: sh install.sh

      - name: Chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'

  centos:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on centos
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh install.sh

      - name: Chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on fedora
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh install.sh

      - name: Chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run ShellCheck
        env:
          SHELLCHECK_OPTS: -e SC1091
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: "yes"

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path=dot_config/nvim/stylua.toml dot_config/nvim/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: format with stylua"
          branch: ${{ github.head_ref }}

  shfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install shfmt
        run: GO111MODULE=on go install mvdan.cc/sh/v3/cmd/shfmt@v3.3.0

      - name: List files to shfmt
        run: shfmt -f .

      - name: Run shfmt
        run: shfmt -w -i 2 -bn -ci -kp .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: format with shfmt"
          branch: ${{ github.head_ref }}

  # typos:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Check spelling of file.txt
  #       uses: crate-ci/typos@master
