name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on macos
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Install requisites on ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo add-apt-repository ppa:fish-shell/release-3
          sudo apt-get update

      - name: Chezmoi Init
        if: ${{ runner.os != 'Windows' }}
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro

      - name: Chezmoi Init on windows
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          iex "& { $(irm https://chezmoi.io/get.ps1) } "
          .\bin\chezmoi init --apply gametaro

  centos:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: centos:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on centos
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro

  fedora:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on fedora
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply gametaro
