name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on macos
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Install requisites on ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install -y curl sudo

      - name: Chezmoi Init
        run: sh install.sh

      - name: Chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'

  centos:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on centos
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh install.sh

      - name: Chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requisites on fedora
        run: dnf clean all && dnf install -y curl sudo

      - name: Chezmoi Init
        run: sh install.sh

      - name: Chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
