name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Chezmoi Init
        if: ${{ runner.os != 'Windows' }}
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin" init --apply --branch "$BRANCH_NAME" "$GITHUB_REPOSITORY_OWNER"
      - name: Chezmoi Init (windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          (irm -useb https://get.chezmoi.io/ps1) | powershell -c -
          bin/chezmoi.exe init --apply --branch "$BRANCH_NAME" "$GITHUB_REPOSITORY_OWNER"
  # centos:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   container: centos:latest
  #   steps:
  #     - uses: actions/checkout@v3
  #
  #     - name: Install requisites (centos)
  #       run: dnf clean all && dnf install -y curl sudo
  #
  #     - name: Chezmoi Init
  #       run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply "$GITHUB_REPOSITORY_OWNER"

# fedora:
#   runs-on: ubuntu-latest
#   timeout-minutes: 15
#   container: fedora:latest
#   env:
#     BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
#   steps:
#     - uses: actions/checkout@v3
#
#     - name: Install requisites (fedora)
#       run: dnf clean all && dnf install -y curl sudo
#
#     - name: Chezmoi Init
#       run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply --branch "$BRANCH_NAME" "$GITHUB_REPOSITORY_OWNER"
