name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    uses: ./.github/workflows/format.yml
    secrets: inherit
  lint:
    uses: ./.github/workflows/lint.yml
  linux:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu:latest
            run: apt-get update -q && apt-get install -y -q curl sudo
          - os: debian:latest
            run: apt-get update -q && apt-get install -y -q curl sudo
          # - os: quay.io/centos/centos:stream
          - os: fedora:latest
            run: dnf clean all && dnf install -y -q curl sudo
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: ${{ matrix.run }}
      - name: Chezmoi init & apply
        run: ./install.sh
  macos:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Chezmoi init & apply
        run: ./install.sh
  windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Chezmoi init & apply
        shell: pwsh
        run: |
          (irm -useb https://get.chezmoi.io/ps1) | powershell -c -
          bin/chezmoi.exe init --apply --source $Env:GITHUB_WORKSPACE
  release:
    needs:
      - format
      - lint
      - linux
      - macos
      - windows
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: dotfiles
      - uses: actions/checkout@v3
      - name: tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Latest Stable Release"
          git push origin stable
