name: Deps
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  lazy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Chezmoi init & apply
        run: ./install.sh
      - name: Chezmoi add
        run: chezmoi add "$HOME/.config/nvim/lazy-lock.json"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "chore(deps): bump nvim plugins"
          commit-message: "chore(deps): bump nvim plugins"
          labels: dependencies
