name: Deps
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  lazy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nick-fields/retry@v2
        name: Chezmoi init & apply
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: ./install.sh
      - name: Chezmoi add
        run: chezmoi add "$HOME/.config/nvim/lazy-lock.json"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          branch: create-pull-request/bump-nvim-plugins
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "chore(deps): bump nvim plugins"
          commit-message: "chore(deps): bump nvim plugins"
          labels: dependencies
  chezmoi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nick-fields/retry@v2
        name: Chezmoi init & apply
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: ./install.sh
      - name: Chezmoi upgrade
        run: |
          CURRENT_VERSION=$(cat .chezmoiversion)
          NEW_VERSION=$(chezmoi data | jq .chezmoi.version.version --raw-output)
          if [ "$CURRENT_VERSION" != "$NEW_VERSION" ]; then
            echo "$NEW_VERSION" > .chezmoiversion
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          branch: create-pull-request/bump-chezmoi
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "chore(deps): bump chezmoi"
          commit-message: "chore(deps): bump chezmoi"
          labels: dependencies
