name: Lint
on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_LUA: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          LINTER_RULES_PATH: /
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: WARN
